# Generated by Django 4.2 on 2023-05-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('postition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_cred.position')),
            ],
        ),
    ]
