# Generated by Django 4.2 on 2023-05-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_cred', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='fullname',
        ),
    ]
