# Generated by Django 4.2 on 2023-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_cred', '0002_rename_first_name_employee_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='postition',
            new_name='position',
        ),
    ]
