# Generated by Django 4.2 on 2023-05-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_cred', '0003_rename_postition_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='titile',
            new_name='title',
        ),
    ]
